### ISSUE TITLE
Blue Rose method

### ISSUE THREAD

**Issue by jeffgillean** [aiterusawato/guides#1]
This isn't the most efficient method of breeding blue roses, but it has the benefit of being easy to follow and guaranteed to work -- no guesswork or genotype-proving techniques are required since each resulting phenotype is unique (e.g. rw x [Y] yields only one possible genotype expressing a red phenotype: ryw). It may be a good place to start since the guide currently has no method.

[Rb] x [Rb] &#8594; R (black, 25%)
[w] x [w] &#8594; W (purple, 25%)
R x W &#8594; rw (red, 100%)
rw x [Y] &#8594; ryw (red, 25%)
ryw x ryw &#8594; RYW (blue, 1.6%)

**Comment by aiterusawato** [comment]
Just added a blue rose route found by Asteriation, which is unambiguous too, has the same chances as yours in the long run, but only needs only 4 seps.

**Comment by tiansh** [comment]
I'm using this approach. Since Red2001xRed2001=Black2000, and, White0010xWhite0010=Purple0020, only require seed bag, and could be done simultaneously. This approach is effective. And you can get Purple, Pink and Black also.  Black could be used to made Gold ones later.
