### ISSUE TITLE
Clarification on child flowers from the reproduction algorithm

### ISSUE THREAD

**Issue by ragzilla** [aiterusawato/guides#2]
Is it known if new flowers produced during the reproduction algorithm, are eligible further on in the algorithm?  E.g. if you had a flower layout of [T2][C][T1][B] where T/B/C were parent, partner, and child respectively (T1 being the first parent/tile chosen in algorithm, and T2 being the second).  Could T2 potentially choose C as a breeding partner when it's processed, or is C marked invalid when spawned?

**Comment by aiterusawato** [comment]
Any flower participating in breeding or cloning is then marked invalid for the whole duration of the algorithm. This will be made clear on the upcoming update.
